server:
  port: 8080
spring:
  application:
    name: gateway-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

zuul:
  routes:
    user-service:
      serviceId: user-service
      url: http://localhost:8081

jms:
  queue:
    gateway-user: gateway-user-queue