server:
  port: 8082
spring:
  application:
    name: rollback-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: rollback_service



